name: CI/CD Pipeline y Seguridad ZAP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4 # Actualizado para quitar el warning de deprecación

    - name: Configurar Java JDK
      uses: actions/setup-java@v4 # Actualizado para la versión más reciente
      with:
        java-version: '25' # Alineado con la versión de tu pom.xml
        distribution: 'temurin'

    - name: Dar permisos al Maven Wrapper
      run: chmod +x mvnw
      working-directory: ./saas-cobranza # Le indicamos dónde está el archivo

    - name: Compilar y Ejecutar Pruebas Unitarias
      run: ./mvnw test
      working-directory: ./saas-cobranza # Le indicamos dónde compilar

    - name: Levantar Spring Boot en segundo plano (Test Environment)
      run: nohup ./mvnw spring-boot:run &
      working-directory: ./saas-cobranza
      env:
        # Aquí inyectas la variable si usas secrets, de lo contrario la pones en duro para la prueba
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 

    - name: Esperar a que el servidor inicie
      run: sleep 30

    - name: Escaneo de Seguridad con OWASP ZAP (Baseline)
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:8080/api/empleados/login'
        fail_action: false
